# Generated by Django 6.0.4 on 2026-05-09 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_founditem_lostitem_comment_claimrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='claimrequest',
            unique_together={('user', 'lost_item', 'found_item')},
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.founditem')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lostitem')),
            ],
        ),
    ]
