# Generated by Django 6.0.4 on 2026-05-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_claimrequest_unique_together_matchhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='found_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.founditem'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='lost_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lostitem'),
        ),
    ]
