# Generated by Django 6.0.4 on 2026-05-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='found_item',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='lost_item',
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.lostitem'),
        ),
    ]
