# Generated by Django 6.0.4 on 2026-05-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_comment_found_item_remove_comment_lost_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='date_found',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='status',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment'),
        ),
        migrations.AddField(
            model_name='founditem',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.lostitem'),
        ),
    ]
