# Generated by Django 6.0.4 on 2026-05-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_founditem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='category',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
